name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Install
      run: go install
    - name: chmod +x
      run: chmod +x /Users/runner/go/bin/goplist
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "/Users/runner/go/bin/goplist"
        omitBody: true
        token: ${{ secrets.GITHUB_TOKEN }}
